name    'lfisher47-pam'
version '0.0.2'
author  'Leah Fisher'
license 'Apache2'
project_page 'https://github.com/lfisher47/puppet-pam'
source  'git://github.com/lfisher47/puppet-pam'
summary 'PAM STIG requirements'
description 'PAM STIG requirements'
dependency 'puppetlabs/inifile'
